### ISSUE TITLE
OIDC AuthService error: Auth failed: cant perform login redirect

### ISSUE THREAD

**Issue by danaabhi** [Misha999777/auth-oidc#4]
I am using this plugin in my react + capacitor app, where i want to login when i click a button it open up everything but when redirect comes it shows error as 

OIDC AuthService error: Auth failed: cant perform login redirect

I have attach image of keycloak Authentication flow, in which OIDC CIBA Grant is disable how can we use different flow

![image](https://github.com/Misha999777/auth-oidc/assets/36625345/cf3146e9-7224-41a6-b5e9-bc52ccc3ac35)

![image](https://github.com/Misha999777/auth-oidc/assets/36625345/11453e4d-5266-4b45-a40d-8c248097c01e)

**Comment by Misha999777** [comment]
Hello,

Recently there were changes made to how Electron/Capacitor redirects are handled: now you can specify an arbitrary callback URL passing it in a config object or specifying it directly in login/logout functions.

Here is an example:
```
new AuthService({
    authority: "http://[host]/realms/[realm-name]",
    clientId: "[client-name]",
    callbackUrl: "http://[host]/[page]"
})
```
You can try it with the latest version `auth-oidc@0.1.0`

Also, the Standard flow in Keycloak should be enough to authenticate.

**Comment by Misha999777** [comment]
I am closing this issue because of the recent changes to the mentioned functionality.
In case the issue persists, please open a new issue.
